### ISSUE TITLE
Set up Patreon

### ISSUE THREAD

**Issue by nolanlawson** [tootcafe/discussions#1]
It's not sustainable for me to do this by myself. I've already heard some folks say they'd chip in, so I think it's time to set up a Patreon.

**Comment by karlprieb** [comment]
When you @nolanlawson will create a Patreon page?

I think it is a good service to keep tracking of donations and monthly costs.

**Comment by nolanlawson** [comment]
Patreon acquired: https://www.patreon.com/user?u=5535137
