### ISSUE TITLE
Toot.Cafe Tusky app

### ISSUE THREAD

**Issue by nolanlawson** [tootcafe/discussions#17]
It's a bit annoying to use Tusky if you have multiple accounts, because you can only have one. Seems we should be able to:

1. Fork Tusky
2. Change the app ID and name
3. Set up our own FCM/GCM account
4. (Optional) change the background to purple

The other option is to add account-switching to Tusky, but this seems faster and also kind of nice to just have Toot.Cafe in my app drawer. 😁

**Comment by halkeye** [comment]
a third option is to add web push to the actual app

**Comment by zaferayan** [comment]
Also toot filtering based on language would be cool on fediverse.

**Comment by sorin-davidoi** [comment]
@halkeye We now have web push: https://github.com/tootsuite/mastodon/pull/3243
