### ISSUE TITLE
Moderator account links are incorrect on about page

### ISSUE THREAD

**Issue by nikhita** [tootcafe/discussions#20]
Just a cosmetic but thought I'll mention it anyway.

On this page: https://toot.cafe/about/more, the moderator accounts mentioned do not point to the correct links.

* `@ohhoe` points to https://toot.cafe/@nolan
* `@halkeye` points to https://toot.cafe/@ohhoe

**Comment by halkeye** [comment]
OOh

I got this one

**Comment by halkeye** [comment]
Thanks @nikhita 

Fixed

**Comment by halkeye** [comment]
@nolanlawson (Can you close this)

**Comment by nikhita** [comment]
Closing @halkeye
