### ISSUE TITLE
Auto-refresh seems broken, 502 web socket error

### ISSUE THREAD

**Issue by nolanlawson** [tootcafe/discussions#22]
See thread: https://toot.cafe/@olpe/198616

I did an upgrade to v1.1.1 a week ago and v1.2 a few days ago, possible that I broke something.

**Comment by nolanlawson** [comment]
Bizarre, I've restarted Sidekiq, I've restarted Nginx, Sidekiq isn't showing any errors in the logs, but I'm still seeing 502 bad gateways for all WebSocket connections. 😕 I'll keep digging...

**Comment by halkeye** [comment]
The streaming server is the JavaScript one right?

Is that running. Does it have logs? Did you check the nohup thingie?

**Comment by nolanlawson** [comment]
good point, I will isolate that one, restart it, and check its logs

**Comment by luisbg** [comment]
I think I am hitting this issue as well. Since the timelines don't auto-update anymore for me, I need to do an F5 refresh of the page to see notifications.

**Comment by nolanlawson** [comment]
Hm I'm seeing occasional errors but I did get a successful 101 connection. The npm process had died for some reason.

Error:

```
ERR! eac5aadd-82a9-486a-8bd0-758c23afb577 Error: Missing access token
ERR! eac5aadd-82a9-486a-8bd0-758c23afb577     at authenticationMiddleware (/home/mastodon/live/streaming/index.js:126:17)
ERR! eac5aadd-82a9-486a-8bd0-758c23afb577     at Layer.handle [as handle_request] (/home/mastodon/live/node_modules/express/lib/router/layer.js:95:5)
ERR! eac5aadd-82a9-486a-8bd0-758c23afb577     at trim_prefix (/home/mastodon/live/node_modules/express/lib/router/index.js:312:13)
ERR! eac5aadd-82a9-486a-8bd0-758c23afb577     at /home/mastodon/live/node_modules/express/lib/router/index.js:280:7
ERR! eac5aadd-82a9-486a-8bd0-758c23afb577     at Function.process_params (/home/mastodon/live/node_modules/express/lib/router/index.js:330:12)
ERR! eac5aadd-82a9-486a-8bd0-758c23afb577     at next (/home/mastodon/live/node_modules/express/lib/router/index.js:271:10)
ERR! eac5aadd-82a9-486a-8bd0-758c23afb577     at allowCrossDomain (/home/mastodon/live/streaming/index.js:77:3)
ERR! eac5aadd-82a9-486a-8bd0-758c23afb577     at Layer.handle [as handle_request] (/home/mastodon/live/node_modules/express/lib/router/layer.js:95:5)
ERR! eac5aadd-82a9-486a-8bd0-758c23afb577     at trim_prefix (/home/mastodon/live/node_modules/express/lib/router/index.js:312:13)
ERR! eac5aadd-82a9-486a-8bd0-758c23afb577     at /home/mastodon/live/node_modules/express/lib/router/index.js:280:7
ERR! eac5aadd-82a9-486a-8bd0-758c23afb577  { [Error: Missing access token] statusCode: 401 }
```

**Comment by nolanlawson** [comment]
Note that previously I had all the logs piped into a single file, but now I'm separating them out so I can do better debugging. Let's watch the current npm process and see how things go.

**Comment by nolanlawson** [comment]
Just confirmed that I am seeing new notifications/toots without needing to refresh. There are still lots of these 401 errors in the logs, but it's working for me on two different browsers. Can anyone else confirm what they're seeing?

**Comment by nolanlawson** [comment]
BTW I also updated our nginx config based on the new [Production Guide](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Production-guide.md) and restarted nginx so that may have helped. Closest issue I found to describe what we saw is https://github.com/tootsuite/mastodon/issues/809

**Comment by luisbg** [comment]
It works now. Thanks :smiley:
