### ISSUE TITLE
Update to Mastodon v1.3.1

### ISSUE THREAD

**Issue by nolanlawson** [tootcafe/discussions#28]
- https://github.com/tootsuite/mastodon/releases/tag/v1.3.1
- https://github.com/tootsuite/mastodon/releases/tag/v1.3

**Comment by gled-rs** [comment]
You should wait a bit, a few issues still on v1.3.1 ( or patch manually ).
https://github.com/tootsuite/mastodon/issues/2551
https://github.com/tootsuite/mastodon/issues/2550
https://github.com/tootsuite/mastodon/pull/2546

;)

**Comment by nolanlawson** [comment]
Thanks for the heads up! Remind me to always wait a few days after a Mastodon release… 😅

**Comment by gled-rs** [comment]
yes, I just deactivated my auto update ansible cron for that same exact reason ;)

**Comment by nolanlawson** [comment]
1.3.2 looks pretty stable: https://github.com/tootsuite/mastodon/releases/tag/v1.3.2

**Comment by nolanlawson** [comment]
I've rebased us on top of 1.3.2: https://github.com/tootcafe/mastodon/commits/master
