### ISSUE TITLE
Round toot.cafe icon

### ISSUE THREAD

**Issue by zoetrope69** [tootcafe/discussions#33]
On the new versions of Android icons are round. Twitter's PWA has a round icon for example.

Could toot.cafes be round? I'm not precious on the idea tbh just a thought. I'm happy to mock it up too?

**Comment by nolanlawson** [comment]
I think there is a new Chrome manifest API that can automatically apply the rounding? It varies among different Android distros, so not all of them are round.

**Comment by zoetrope69** [comment]
Looks like its a wip: https://github.com/w3c/manifest/pull/657

Will close for now

**Comment by NotWoods** [comment]
That spec landed and Firefox and Chrome are now implementing support! You may want to revist creating a [maskable icon](https://css-tricks.com/maskable-icons-android-adaptive-icons-for-your-pwa/).
