### ISSUE TITLE
image file upload hangs

### ISSUE THREAD

**Issue by forresto** [tootcafe/discussions#34]
I don't see errors in the console, and the network tab shows that the media post was 402 OK.
![image](https://user-images.githubusercontent.com/395307/200408874-c697d385-677d-4a27-96e0-e0ee5fe3ae31.png)

`preview_url` is [live](https://assets.toot.cafe/media_attachments/files/109/304/408/591/439/239/small/89ce0417852d4e22.png). And [original](https://assets.toot.cafe/media_attachments/files/109/304/408/591/439/239/original/89ce0417852d4e22.png).

But the "Toot!" button does not re-enable itself.
![image](https://user-images.githubusercontent.com/395307/200408972-813442b7-b21a-4b77-bdff-948b0fada982.png)

**Comment by forresto** [comment]
I'd missed this, a strong hint that it might be time to find a new instance: https://toot.cafe/web/@nolan/109295594146276613

**Comment by nolanlawson** [comment]
Yeah the server load has been nuts recently. I'm trying to get a handle on it.
