### ISSUE TITLE
Favicon and GitHub org icon

### ISSUE THREAD

**Issue by nolanlawson** [tootcafe/discussions#4]
I think it'd be nice to have a favicon and an icon for this GitHub org; I was thinking maybe a coffee cup or something but I'm open to suggestions. Looked around and didn't find a lot of Creative Commons coffee cup images, but since we have some designers in the house, maybe it'd be good to ask among the community?

**Comment by mlcdf** [comment]
My modest contribution.

![logo](https://cloud.githubusercontent.com/assets/9364931/24840519/aac8e0aa-1d6e-11e7-8ba0-acbd7f52854f.png)

Feel free to leave your feedback!

**Comment by nolanlawson** [comment]
I really love all of these, especially the cup with a heart in it (simple and recognizable even at low resolutions, great for a favicon! 😃).

**Comment by mlcdf** [comment]
Yeah, that's the one I prefer too. I also didn't another iteration based on [@Gargoylezoo](https://physi.cc/@Gargoylezoo) feedback: 

![4abeaf4ee02469c7](https://cloud.githubusercontent.com/assets/9364931/24946402/1072ede2-1f63-11e7-98ae-0ab79d7bbdad.png)

While I loved the idea (drawing a trumpet with the coffee creme), I doesn't work very well in practice  (and also, it's poorly made). A trumpet having a lot more details than a heart, at low resolution, you simply can't tell it's a trumpet.

I'm gonna make a set of SVG (for Android, iOS and the web) for the cup with a heart in it (in order t.o see what it looks like in practice)

**Comment by mlcdf** [comment]
I created a repository to host the icons (as well as the color theme) so people can use them if they want: https://github.com/mlcdf/tootcafe-ressources

If we go with this icon, then I'll transfer the repo to the TootCafe organization.

**Comment by nolanlawson** [comment]
I love it! I'll add these ASAP. :)

**Comment by nolanlawson** [comment]
Done! We are logo'd. Awesome work! 🎉🎉🎉

**Comment by rtorr** [comment]
Id love this to also work for Androids add to home screen icon 👌

**Comment by mlcdf** [comment]
Thanks! :blush: 

I transfered the repository to our GitHub org: https://github.com/tootcafe/ressources

Damn, I forgot that in English, it's `resources` and not `ressources`. @nolanlawson if you can rename the repo & update its description.

**Comment by mlcdf** [comment]
@rtorr Yeah, that would be great. We need to update the manifest.json for that.
