### ISSUE TITLE
Improve SSL score

### ISSUE THREAD

**Issue by nolanlawson** [tootcafe/discussions#5]
I'm told we currently score a B; I used LetsEncrypt with some pretty basic setup but I know this can be improved. Especially for a tech-savvy crowd it would probably be best to have a good score there. 😅

**Comment by Pajn** [comment]
Here are some results: https://observatory.mozilla.org/analyze.html?host=toot.cafe

**Comment by ramlmn** [comment]
Same thing on SSL Labs [https://www.ssllabs.com/ssltest/analyze.html?d=toot.cafe](https://www.ssllabs.com/ssltest/analyze.html?d=toot.cafe)

**Comment by nolanlawson** [comment]
We're now up to a B+ on Observatory and A+ on SSLLabs after I updated our nginx config. More work left to do. :)

**Comment by nolanlawson** [comment]
Observatory wants us to add a CSP header, wondering if this is the fix: https://github.com/tootsuite/mastodon/pull/1380

**Comment by nolanlawson** [comment]
We're now an A- on Observatory (https://observatory.mozilla.org/analyze.html?host=toot.cafe) after I added this CSP:

    add_header Content-Security-Policy "default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self' wss://toot.cafe; upgrade-insecure-requests";

Observatory wants us to make it even stricter to get up to an A+ but I'm not sure we can. Also I don't quite understand why Mastodon itself doesn't send a CSP header (we're on v1.2), but maybe this is fixed in v1.2.1?

**Comment by nolanlawson** [comment]
OK we now get an A+ from Observatory. Here's the new CSP. Seems not to be too strict because everything is functioning in both Firefox and Chrome AFAICT:

    add_header Content-Security-Policy "default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self'; img-src 'self' data:; object-src 'self'; media-src 'self'; connect-src 'self' wss://toot.cafe; upgrade-insecure-requests";

**Comment by nolanlawson** [comment]
FWIW we also get A+ here: https://tls.imirhil.fr/https/toot.cafe

**Comment by nolanlawson** [comment]
Observatory has downgraded us to A- because I had to revert the `script-src`: https://github.com/tootcafe/discussions/issues/24 😛
