### ISSUE TITLE
Opening up registration on a regular basis

### ISSUE THREAD

**Issue by nolanlawson** [tootcafe/discussions#7]
Other instances like witches.town and cybre.space seem to be doing this: opening up registrations, say, every day for an hour at 9am. (Good to control the flood of users.) Should we start doing this?

All signs indicate that we could probably comfortably hold another 100 users or so, but I don't want to get cocky and then have the server get sluggish and then go down while I upgrade. Also I'm a bit worried about trolls getting in because I'm already starting to attract some attention. But presumably we could handle that at the moderator level.

**Comment by halkeye** [comment]
My vote is make it easier to invite people at least for the short term. There's enough other instances that nobody should be desperate. I have pretty public contact info as well

**Comment by gladimdim** [comment]
I would allow refugees from twitter,  but related to webdev accounts. There are enough other instances,  so they have place to chat about lgbt/nazis problems :)

**Comment by AntonioVdlC** [comment]
On one hand, it is really tempting to follow the steps of `witches.town` and `cybre.space`, as I think they are great communities and I think we should be open to anyone that might be interested in joining us, but the risk is to overflood the `toot.cafe` instance.

On the other hand, I don't know how tedious it is to invite people manually, but that definitely won't scale (if what we want as a community is to grow `toot.cafe` indefinitely). Besides, that narrows a bit the diversity of people who can join as only your Twitter followers can ask for an invite! 😝 

So, my take is to do an hybrid of both, where we announce an opening hour (so that people who are interested in joining our community can) and let in a certain number of people per day (so that we can scale at a manageable rhythm, both server-wise and also people- and culture-wise).

**Comment by nolanlawson** [comment]
> that narrows a bit the diversity of people who can join as only your Twitter followers can ask for an invite! 

Actually my DMs are open and have been for years. :) Usually it's not worked out too badly for me, but we'll see how much longer that can last.

The other thing to know is that the current invite process is _extremely_ manual. It's a lot of pointing and clicking and copying and pasting and asking people to _please_ provide both an email address and a username and navigating the Twitter DM UI which gets real unusable when you have more than 100 or so DMs. Recently it's also a lot of vetting people's Twitter profiles to avoid trolls. Luckily I'm a fast typist so it's not too bad, but still very taxing and time-consuming.

I would love if there were a better system, but I did some research and it seems it's only possible to whitelist registrations for particular *domains*. I suppose this works for people who have email addresses at their own domains (which TBF is a lot of our target audience) but it still doesn't include everyone. So that's another reason I'm looking into open signups: to make things less exhausting for myself. 😛

Maybe the whitelist-by-domain approach is a good compromise while we work something better out. It's as easy for me as concatenating a string from a bunch of domains, setting a config in Mastodon, and then restarting the server.

**Comment by halkeye** [comment]
I've been working on and off all afternoon to get a dev setup going (havn't used vagrant in years). Once I do, invites is something I want to tackle

**Comment by nolanlawson** [comment]
Maybe we should just open up a PR on Mastodon itself? This seems like a generally useful feature. Just a pipe-separated list of email address in a config or something.

**Comment by AntonioVdlC** [comment]
> Actually my DMs are open and have been for years. :) Usually it's not worked out too badly for me, but we'll see how much longer that can last.

Oh well, I guess I'm the only person I know that doesn't have open DMs ... that makes my argument void! 😅 

> The other thing to know is that the current invite process is extremely manual. It's a lot of pointing and clicking and copying and pasting and asking people to please provide both an email address and a username and navigating the Twitter DM UI which gets real unusable when you have more than 100 or so DMs. Recently it's also a lot of vetting people's Twitter profiles to avoid trolls. Luckily I'm a fast typist so it's not too bad, but still very taxing and time-consuming.

Ultimately it's up to you! I feel like it's either whitelisting or blacklisting, with the former being extremely tedious, until we work out a better solution in the code itself. I feel like we can talk about this for ages, but the best way to figure it out is definitely to try it out and see what works best (or just decide to do nothing)!

**Comment by nolanlawson** [comment]
Yeah I still wouldn't be opposed at this point to just opening up registrations for an hour or two. We've got a moderator team that is slowly growing, and supposedly people who are interested in the same kind of stuff are likely to join, but it's also not required that everything be on-topic all the time and it's frequently not already anyway, and the timeline is still a great experience.

Also a flood of new users tends to create an uptick in usage which is neat to watch.

**Comment by Pajn** [comment]
As the invitations put quite a strain on Nolan I think we should open. However, I think we should modify the about page a bit first as it's just a stock Mastodon page. Just some things makes it more likely that people join because the want to join toot.cafe instead of any random Mastodon instance. Like pointing out that we have what might be considered a pretty strict CoC and do have some instances blocked and a easier to spot link to the about/more page.
I'm not that good on writing texts but if anyone want to do that but don't want to set up a dev version on Mastodon I can take that part.

**Comment by mlcdf** [comment]
> I feel like we can talk about this for ages, but the best way to figure it out is definitely to try it out and see what works best (or just decide to do nothing)!

Yeah, so do I. Let's just do this then:

> opening up registrations for an hour or two.

And we'll see how that goes.

**Comment by rachelnicole** [comment]
If you're going to be upset with people discussing social justice / lgbtq* issues / *-isms then toot.cafe is not going to be the place for you. There are already enough silos on the internet for people to discuss programming, and while the instance is initially being seeded by the dev community, people are (hopefully) more complex than just talking about programming so natural normal conversations are going to happen.

This isn't going to be the place where people tweet "I like your account a lot more when you don't talk about X"

**Comment by halkeye** [comment]
I'm not saying no to open reg, even though it adds work for us mods. I just want to make invites easier.

@nolanlawson would just having a create interface for making users be good enough to lessen the load on you? or the slightly more complicated flat import of emails be the best?

**Comment by bytesbymike** [comment]
I think ease of config for @nolanlawson (and others) is the most important thing.

It happens to be cool right now that toot.cafe is that it's small enough to keep up with the local timeline, but I wouldn't suggest that's a reason to be overly restrictive or exclusionary!

Oh, maybe add some "about" text speaking to Rachel's point about it not be *strictly* tech focused.

My $0.02.

**Comment by halkeye** [comment]
with https://github.com/scambra/devise_invitable and a bit of work, it would allow any user to invite any other person they want. It would allow organic growth without a free for all.

I'm working on an admin interface for creating a new user right now.

Want to prototype some other ideas for inviting users (livejournal back in the day had accounts have a limited number invite codes which i actually liked)

**Comment by nolanlawson** [comment]
After listening to discussion, I agree with @halkeye and @rachelnicole and would like to seed deliberately a bit longer. @halkeye's system sounds great but I would also be happy with just a PR to Mastodon to allow a config for whitelisted email addresses. Alternatively, for anybody who has an email with a unique domain such a config already exists.

Also yeah there will undoubtedly be LGBTQ/anti-Nazi/etc. discussions on toot.cafe, especially since it's kinda part of the culture of Mastodon as a whole. The thing about an instance is that it's not required to be about a particular topic or set of topis; it's more about social connections and community. Once you use it enough and you've curated your follows, you'll probably find yourself less frequently watching the Local/Federated Timelines and rather just staying in Home. In the meantime it's a social network like any other; you can mute and unfollow accounts as you see fit, so nobody has to feel like they need to stay on-topic all the time. 🙂

**Comment by luisbg** [comment]
Maybe we could keep a file in this repo with latest numbers on users and usage. See how much space for growth there is before the gates are open again.

**Comment by luisbg** [comment]
Re-read this. Is there a way for the rest of moderators to help and have new joiners not put as much of a strain on @nolanlawson ?

**Comment by nolanlawson** [comment]
@luisbg I'll DM you. :)

**Comment by nolanlawson** [comment]
OK I think I'm going to go with @amycheng's system: https://github.com/amycheng/mastodon/pull/1. We'll have open registration but you need a URL-param-based passphrase to get in. We can change the passphrase periodically or close it down as needed.

This will ensure we can send URLs to our friends to let them sign up, but we won't show up on generic tools like instances.mastodon.xyz or tooter.today where people just want to sign up for any old Mastodon instance.

**Comment by nolanlawson** [comment]
Fixed by https://github.com/tootcafe/mastodon/pull/9 and https://github.com/tootcafe/mastodon/pull/10, we now have a passphrase-based registration system.
