### ISSUE TITLE
Update Mastodon to v1.1.1

### ISSUE THREAD

**Issue by halkeye** [tootcafe/discussions#8]
Not sure its a discussion, but https://github.com/tootsuite/mastodon/releases/tag/v1.1.1

**Comment by halkeye** [comment]
Apparently I can't label anyways

**Comment by halkeye** [comment]
https://mastodon.at/users/pfigel/updates/689

how to update with no downtime

**Comment by nolanlawson** [comment]
Awesome thank you, I was actually waiting for them to adopt a real versioning system before upgrading. up to now it's just been pulling from github master, which has had its issues (people have had to downgrade because o fa bug). I'll rebase our changes and get this done as soon as I can!

**Comment by nolanlawson** [comment]
Fixed by https://github.com/tootcafe/mastodon/pull/4
