### ISSUE TITLE
Policy on fake accounts

### ISSUE THREAD

**Issue by nolanlawson** [tootcafe/discussions#9]
Some people are worried about fake accounts on Mastodon parading as other users, but our current CoC does not mention what to do in the case of such accounts. Arguably in the case of celebrity impersonators and such, these can be funny and good-hearted and not trying to actually impersonate someone.

What policy should we have on this? Should we take it on a case-by-case basis?

**Comment by halkeye** [comment]
I assume for example:
https://mastodon.technology/@twitter
https://mastodon.cloud/@realDonaldTrump

My vote is unless they are on the toot.cafe server, they are kinda not our problem

**Comment by nolanlawson** [comment]
That makes sense; I was thinking more about accounts on toot.cafe itself.

**Comment by Pajn** [comment]
My vote is on not allowing them on toot.cafe, we have a bit more personal community more in line with witches.town and toot.cat than mastodon.social and I would love if we could keep it there.
One can still follow them if you want and I guess at least some of them will show up in the federated timeline.
So I don't want them banned or muted, just on a bit longer distance.

**Comment by halkeye** [comment]
Huh you can't add reactions on mobile? I agree with Pajn. Do nothing for the universe at large but disallow locally

**Comment by nolanlawson** [comment]
That sounds about right to me. Also fake accounts that are trying to impersonate someone who's *not* a celebrity (i.e. it's not immediately obvious it's a joke) should probably be blocked outright, remote or otherwise. Not sure how to word that in the terms though.

**Comment by nolanlawson** [comment]
This seems pretty obvious; I'm going to just say we ban fake accounts entirely. I would rather people just be themselves on toot.cafe anyway; you can have joke celebrity accounts elsewhere and that's cool.

**Comment by nolanlawson** [comment]
Updated rule:

> No fake accounts, even celebrity joke accounts. Note this rule does not necessarily apply to remote accounts.
